-   id: copyright-checker
    name: Pivotal Copyright Checker
    description: Ensure that the copyright is on python files
    entry: copyright-checker
    language: python
    types: [text]
    exclude: '^.git/|^.idea/|^.venv/|migrations/'
    minimum_pre_commit_version: 0.15.0