-   id: copyright_checker
    language: system
    name: Pivotal Copyright Checker
    entry: copyright_checker
    files: .py
    types: [file, python]
    exclude: '^.git/|^.idea/|^.venv/|migrations/'
    minimum_pre_commit_version: 0.15.0